services:
  mysql:
    image: mysql:8.0

    container_name: torneio_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: torneio

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./banco/banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  mysql_data: